version: "3.9"

services:

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata_restaurant:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  restaurant-service:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "50053:50053"

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: restaurant_db

      REDIS_HOST: redis
      REDIS_PORT: 6379

      NATS_URL: ${NATS_URL:-nats://nats:4222}

      GRPC_PORT: 50053

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    restart: unless-stopped

volumes:
  pgdata_restaurant: