// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/restaurant.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Restaurant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Rating        float64                `protobuf:"fixed64,4,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restaurant) Reset() {
	*x = Restaurant{}
	mi := &file_proto_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurant) ProtoMessage() {}

func (x *Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurant.ProtoReflect.Descriptor instead.
func (*Restaurant) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *Restaurant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Restaurant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Restaurant) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_proto_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *MenuItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItem) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ListRestaurantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRestaurantsRequest) Reset() {
	*x = ListRestaurantsRequest{}
	mi := &file_proto_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRestaurantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRestaurantsRequest) ProtoMessage() {}

func (x *ListRestaurantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRestaurantsRequest.ProtoReflect.Descriptor instead.
func (*ListRestaurantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{2}
}

type ListRestaurantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*Restaurant          `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRestaurantsResponse) Reset() {
	*x = ListRestaurantsResponse{}
	mi := &file_proto_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRestaurantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRestaurantsResponse) ProtoMessage() {}

func (x *ListRestaurantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRestaurantsResponse.ProtoReflect.Descriptor instead.
func (*ListRestaurantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *ListRestaurantsResponse) GetRestaurants() []*Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

type GetRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantRequest) Reset() {
	*x = GetRestaurantRequest{}
	mi := &file_proto_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantRequest) ProtoMessage() {}

func (x *GetRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *GetRestaurantRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurant    *Restaurant            `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantResponse) Reset() {
	*x = RestaurantResponse{}
	mi := &file_proto_restaurant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantResponse) ProtoMessage() {}

func (x *RestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantResponse.ProtoReflect.Descriptor instead.
func (*RestaurantResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{5}
}

func (x *RestaurantResponse) GetRestaurant() *Restaurant {
	if x != nil {
		return x.Restaurant
	}
	return nil
}

type SearchItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchItemsRequest) Reset() {
	*x = SearchItemsRequest{}
	mi := &file_proto_restaurant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemsRequest) ProtoMessage() {}

func (x *SearchItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemsRequest.ProtoReflect.Descriptor instead.
func (*SearchItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{6}
}

func (x *SearchItemsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchItemsResponse) Reset() {
	*x = SearchItemsResponse{}
	mi := &file_proto_restaurant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchItemsResponse) ProtoMessage() {}

func (x *SearchItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchItemsResponse.ProtoReflect.Descriptor instead.
func (*SearchItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{7}
}

func (x *SearchItemsResponse) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_proto_restaurant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{8}
}

func (x *GetItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *MenuItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	mi := &file_proto_restaurant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{9}
}

func (x *ItemResponse) GetItem() *MenuItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type RateRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int64                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateRestaurantRequest) Reset() {
	*x = RateRestaurantRequest{}
	mi := &file_proto_restaurant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateRestaurantRequest) ProtoMessage() {}

func (x *RateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*RateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{10}
}

func (x *RateRestaurantRequest) GetRestaurantId() int64 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *RateRestaurantRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RateRestaurantRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RateRestaurantRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RateRestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateRestaurantResponse) Reset() {
	*x = RateRestaurantResponse{}
	mi := &file_proto_restaurant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateRestaurantResponse) ProtoMessage() {}

func (x *RateRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateRestaurantResponse.ProtoReflect.Descriptor instead.
func (*RateRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_proto_rawDescGZIP(), []int{11}
}

func (x *RateRestaurantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_restaurant_proto protoreflect.FileDescriptor

const file_proto_restaurant_proto_rawDesc = "" +
	"\n" +
	"\x16proto/restaurant.proto\x12\n" +
	"restaurant\"j\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x01R\x06rating\"|\n" +
	"\bMenuItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\"\x18\n" +
	"\x16ListRestaurantsRequest\"S\n" +
	"\x17ListRestaurantsResponse\x128\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x16.restaurant.RestaurantR\vrestaurants\"&\n" +
	"\x14GetRestaurantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"L\n" +
	"\x12RestaurantResponse\x126\n" +
	"\n" +
	"restaurant\x18\x01 \x01(\v2\x16.restaurant.RestaurantR\n" +
	"restaurant\"*\n" +
	"\x12SearchItemsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"A\n" +
	"\x13SearchItemsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.restaurant.MenuItemR\x05items\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\fItemResponse\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.restaurant.MenuItemR\x04item\"\x87\x01\n" +
	"\x15RateRestaurantRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x03R\frestaurantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"2\n" +
	"\x16RateRestaurantResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xac\x03\n" +
	"\x11RestaurantService\x12Z\n" +
	"\x0fListRestaurants\x12\".restaurant.ListRestaurantsRequest\x1a#.restaurant.ListRestaurantsResponse\x12Q\n" +
	"\rGetRestaurant\x12 .restaurant.GetRestaurantRequest\x1a\x1e.restaurant.RestaurantResponse\x12N\n" +
	"\vSearchItems\x12\x1e.restaurant.SearchItemsRequest\x1a\x1f.restaurant.SearchItemsResponse\x12?\n" +
	"\aGetItem\x12\x1a.restaurant.GetItemRequest\x1a\x18.restaurant.ItemResponse\x12W\n" +
	"\x0eRateRestaurant\x12!.restaurant.RateRestaurantRequest\x1a\".restaurant.RateRestaurantResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_restaurant_proto_rawDescOnce sync.Once
	file_proto_restaurant_proto_rawDescData []byte
)

func file_proto_restaurant_proto_rawDescGZIP() []byte {
	file_proto_restaurant_proto_rawDescOnce.Do(func() {
		file_proto_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_restaurant_proto_rawDesc), len(file_proto_restaurant_proto_rawDesc)))
	})
	return file_proto_restaurant_proto_rawDescData
}

var file_proto_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_restaurant_proto_goTypes = []any{
	(*Restaurant)(nil),              // 0: restaurant.Restaurant
	(*MenuItem)(nil),                // 1: restaurant.MenuItem
	(*ListRestaurantsRequest)(nil),  // 2: restaurant.ListRestaurantsRequest
	(*ListRestaurantsResponse)(nil), // 3: restaurant.ListRestaurantsResponse
	(*GetRestaurantRequest)(nil),    // 4: restaurant.GetRestaurantRequest
	(*RestaurantResponse)(nil),      // 5: restaurant.RestaurantResponse
	(*SearchItemsRequest)(nil),      // 6: restaurant.SearchItemsRequest
	(*SearchItemsResponse)(nil),     // 7: restaurant.SearchItemsResponse
	(*GetItemRequest)(nil),          // 8: restaurant.GetItemRequest
	(*ItemResponse)(nil),            // 9: restaurant.ItemResponse
	(*RateRestaurantRequest)(nil),   // 10: restaurant.RateRestaurantRequest
	(*RateRestaurantResponse)(nil),  // 11: restaurant.RateRestaurantResponse
}
var file_proto_restaurant_proto_depIdxs = []int32{
	0,  // 0: restaurant.ListRestaurantsResponse.restaurants:type_name -> restaurant.Restaurant
	0,  // 1: restaurant.RestaurantResponse.restaurant:type_name -> restaurant.Restaurant
	1,  // 2: restaurant.SearchItemsResponse.items:type_name -> restaurant.MenuItem
	1,  // 3: restaurant.ItemResponse.item:type_name -> restaurant.MenuItem
	2,  // 4: restaurant.RestaurantService.ListRestaurants:input_type -> restaurant.ListRestaurantsRequest
	4,  // 5: restaurant.RestaurantService.GetRestaurant:input_type -> restaurant.GetRestaurantRequest
	6,  // 6: restaurant.RestaurantService.SearchItems:input_type -> restaurant.SearchItemsRequest
	8,  // 7: restaurant.RestaurantService.GetItem:input_type -> restaurant.GetItemRequest
	10, // 8: restaurant.RestaurantService.RateRestaurant:input_type -> restaurant.RateRestaurantRequest
	3,  // 9: restaurant.RestaurantService.ListRestaurants:output_type -> restaurant.ListRestaurantsResponse
	5,  // 10: restaurant.RestaurantService.GetRestaurant:output_type -> restaurant.RestaurantResponse
	7,  // 11: restaurant.RestaurantService.SearchItems:output_type -> restaurant.SearchItemsResponse
	9,  // 12: restaurant.RestaurantService.GetItem:output_type -> restaurant.ItemResponse
	11, // 13: restaurant.RestaurantService.RateRestaurant:output_type -> restaurant.RateRestaurantResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_restaurant_proto_init() }
func file_proto_restaurant_proto_init() {
	if File_proto_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_restaurant_proto_rawDesc), len(file_proto_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_restaurant_proto_goTypes,
		DependencyIndexes: file_proto_restaurant_proto_depIdxs,
		MessageInfos:      file_proto_restaurant_proto_msgTypes,
	}.Build()
	File_proto_restaurant_proto = out.File
	file_proto_restaurant_proto_goTypes = nil
	file_proto_restaurant_proto_depIdxs = nil
}
